export type PermissionMode = 'default' | 'acceptEdits' | 'plan' | 'bypassPermissions';

export const PERMISSION_MODES: PermissionMode[] = ['default', 'acceptEdits', 'plan', 'bypassPermissions'];

export type Role = 'user' | 'assistant' | 'system';

export type ToolStatus =
  | 'pending'
  | 'confirming'
  | 'running'
  | 'completed'
  | 'failed'
  | 'rejected';

export interface ToolCallState {
  id: string;
  name: string;
  args: Record<string, any>;
  status: ToolStatus;
  /** Raw result sent back to the model (already truncated). */
  result?: string;
  error?: string;
  /** Unified diff (edit_file / write_file) computed against the real file. */
  diff?: string;
  /** Short human summary, e.g. "Read 120 lines". */
  summary?: string;
  startTime?: number;
  endTime?: number;
}

export type MessagePart =
  | { type: 'text'; id: string; content: string }
  | { type: 'tool'; id: string; toolCall: ToolCallState };

export type MessageKind = 'normal' | 'command' | 'bash' | 'compact' | 'notice';

export interface ChatMessage {
  id: string;
  role: Role;
  /** For user/system messages: the text. For assistant: the concatenated text parts. */
  content: string;
  parts?: MessagePart[];
  kind?: MessageKind;
  timestamp: number;
}

export type AgentStatus =
  | 'idle'
  | 'thinking'
  | 'streaming'
  | 'running_tool'
  | 'awaiting_permission'
  | 'compacting';

export type PermissionDecision =
  | { kind: 'yes' }
  | { kind: 'always'; rule: string }
  | { kind: 'no'; feedback?: string };

export interface PermissionOption {
  value: 'yes' | 'always' | 'no';
  label: string;
  /** Rule persisted when value === 'always'. */
  rule?: string;
  /** Switch the permission mode when chosen (e.g. acceptEdits). */
  switchMode?: PermissionMode;
}

export interface PendingConfirmation {
  toolCall: ToolCallState;
  title: string;
  options: PermissionOption[];
  danger?: string;
  onDecide: (decision: PermissionDecision) => void;
}

export interface UsageInfo {
  /** Prompt tokens of the last API call (≈ current context size). */
  promptTokens: number;
  /** Tokens generated by the last API call. */
  responseTokens: number;
  /** Sum of totalTokenCount over all API calls of the session. */
  cumulativeTokens: number;
  contextWindow: number;
  apiCalls: number;
  turns: number;
}

export type TranscriptItem =
  | { key: string; kind: 'banner' }
  | { key: string; kind: 'user'; message: ChatMessage }
  | { key: string; kind: 'system'; message: ChatMessage }
  | { key: string; kind: 'text'; messageId: string; content: string; timestamp: number }
  | { key: string; kind: 'tool'; messageId: string; toolCall: ToolCallState }
  | { key: string; kind: 'turn_end'; messageId: string; durationMs: number; toolCount: number; timestamp: number };

export interface LiveTurn {
  text: string;
  tools: ToolCallState[];
}

export interface Notice {
  text: string;
  level: 'info' | 'warn' | 'error';
}
