export type PermissionMode = 'default' | 'acceptEdits' | 'plan' | 'auto' | 'bypassPermissions';

export const PERMISSION_MODES: PermissionMode[] = ['default', 'acceptEdits', 'plan', 'auto', 'bypassPermissions'];
/** Shift+Tab order, as in Claude Code: manual → accept edits → plan → auto. Bypass joins only when the session started in it. */
export const CYCLE_MODES: PermissionMode[] = ['default', 'acceptEdits', 'plan', 'auto'];

export type Role = 'user' | 'assistant' | 'system';

export type ToolStatus =
  | 'pending'
  | 'confirming'
  | 'running'
  | 'completed'
  | 'failed'
  | 'rejected';

export interface ToolCallState {
  id: string;
  name: string;
  args: Record<string, any>;
  status: ToolStatus;
  /** Result sent back to the model (may be truncated). */
  result?: string;
  /** Full foreground Bash output, saved separately from the model result. */
  outputFile?: string;
  error?: string;
  /** Unified diff (edit_file / write_file) computed against the real file. */
  diff?: string;
  /** Short human summary, e.g. "Read 120 lines". */
  summary?: string;
  /** 'user' for a command typed with "!": shown as the user's own, never folded into a tool summary. */
  origin?: 'user';
  /** exit_plan_mode through the plan dialog: where the plan was saved ('' if it could not be). */
  planFile?: string;
  startTime?: number;
  endTime?: number;
}

export type MessagePart =
  /** `model`: the model that wrote it, shown with the time in the detailed view (Ctrl+O). */
  | { type: 'text'; id: string; content: string; model?: string }
  /** Gemini's thought summary for this step, shown folded as "✻ Thinking…" (Ctrl+O shows it). */
  | { type: 'thinking'; id: string; content: string }
  | { type: 'tool'; id: string; toolCall: ToolCallState };

export type MessageKind = 'normal' | 'command' | 'bash' | 'compact' | 'notice' | 'context' | 'warning' | 'event';

export interface AttachmentMeta {
  name: string;
  mimeType: string;
  bytes: number;
}

export interface ChatMessage {
  id: string;
  role: Role;
  /** For user/system messages: the text. For assistant: the concatenated text parts. */
  content: string;
  parts?: MessagePart[];
  kind?: MessageKind;
  timestamp: number;
  /** Images sent with a user message (metadata only; the bytes live in the model history). */
  attachments?: AttachmentMeta[];
}

/** A background agent shown in the agents view (← on an empty prompt). */
export interface AgentTask {
  id: string;
  title: string;
  status: 'working' | 'completed' | 'failed';
  startedAt: number;
  endedAt?: number;
  /** Last progress line while it works. */
  progress?: string;
  /** Final report, or the error. */
  report?: string;
}

export type AgentStatus =
  | 'idle'
  | 'thinking'
  | 'retrying'
  | 'streaming'
  | 'running_tool'
  | 'awaiting_permission'
  | 'compacting';

/** `plan` is the plan text after the user edited it in the approval dialog (Ctrl+G). */
export type PermissionDecision =
  | { kind: 'yes'; feedback?: string; plan?: string }
  | { kind: 'always'; rule: string; rules?: string[]; feedback?: string; plan?: string }
  | { kind: 'no'; feedback?: string; plan?: string };

export interface PermissionOption {
  value: 'yes' | 'always' | 'no';
  label: string;
  /** Rule persisted when value === 'always'. */
  rule?: string;
  /** Every rule to persist, one per subcommand of a compound Bash command (up to 5). */
  rules?: string[];
  /** Switch the permission mode when chosen (e.g. acceptEdits). */
  switchMode?: PermissionMode;
  /** Add this directory to the workspace for the session when chosen. */
  addDirectory?: string;
}

export interface PendingConfirmation {
  toolCall: ToolCallState;
  title: string;
  options: PermissionOption[];
  danger?: string;
  /** A plain line above the question ("This command requires approval"). */
  note?: string;
  /** exit_plan_mode: the plan shown in the approval dialog, and the file it was saved to. */
  plan?: { text: string; file?: string };
  onDecide: (decision: PermissionDecision) => void;
}

export interface UsageInfo {
  /** Prompt tokens of the last API call (≈ current context size). */
  promptTokens: number;
  /** Tokens generated by the last API call. */
  responseTokens: number;
  /** Sum of totalTokenCount over all API calls of the session. */
  cumulativeTokens: number;
  contextWindow: number;
  apiCalls: number;
  turns: number;
  /** Prompt tokens sent over the session, and how many of them Gemini's cache served. */
  cumulativePromptTokens?: number;
  cumulativeCachedTokens?: number;
  cumulativeResponseTokens?: number;
  cumulativeThoughtsTokens?: number;
  /** Prompt tokens at which the conversation is compacted automatically; absent when auto-compact is off. */
  compactAt?: number;
  /** Old tool outputs cleared from the conversation this session, and the characters they weighed. */
  prunedOutputs?: number;
  prunedChars?: number;
}

export type TranscriptItem =
  | { key: string; kind: 'banner' }
  | { key: string; kind: 'user'; message: ChatMessage }
  | { key: string; kind: 'system'; message: ChatMessage }
  | { key: string; kind: 'text'; messageId: string; content: string; timestamp: number; model?: string }
  | { key: string; kind: 'thinking'; messageId: string; content: string; timestamp: number }
  | { key: string; kind: 'tool'; messageId: string; toolCall: ToolCallState }
  | { key: string; kind: 'turn_end'; messageId: string; durationMs: number; toolCount: number; timestamp: number };

export interface LiveTurn {
  text: string;
  tools: ToolCallState[];
}

export interface Notice {
  text: string;
  level: 'info' | 'warn' | 'error';
}

export type TodoStatus = 'pending' | 'in_progress' | 'completed';

export interface TodoItem {
  content: string;
  status: TodoStatus;
  /** Present-continuous form shown while in progress (e.g. "Running tests"). */
  activeForm?: string;
}
